### ISSUE TITLE
fix_chiken/fix.js

### ISSUE THREAD

**Issue by satopian** [sakots/poti-EVO-themes#9]
`<script href="<% echo(skindir) %>fix_chiken/fix.js"></script>
`
ここに入っているJavaScriptは、ChickenPaintの今回の問題をfixするJavaScriptではありません。
以前はPaintのテーマに入っていて、現在は削除ずみのものです。
その処理は現在はchickenpaint.jsにはいっており、作者の方が作った'ChickenPaint example'のHTMLにもみあたりません。
では、その外部jsを修正すれば問題は解決するでしょうか?
いいえ、iPadなどのデバイスは外部jsを強固にキャッシュしますから、そのjsを書き直しても更新した動作になりません。
NEOのバージョンをあげても更新されないのと同じ問題が起きます。
ChickenPaintそのものの更新で、こちらで特別なfixをしなくてもよくなりそうですが、間違いである事には変わりありません。

**Comment by sakots** [comment]
「間違いであるのがわかっている」のはわかりましたが、「正解を知っているのか知らないのか」がわからないのでそれをお教え願います。

**Comment by satopian** [comment]
> chickenpaintの問題に対処するcss/jsは外部化すべき · Issue #5 · satopian/poti-kaini
> https://github.com/satopian/poti-kaini/issues/5
> 
ここには、
```
function load() {
document.addEventListener("dblclick", function(e){ e.preventDefault();}, { passive: false });
}
window.onload = load;
```
とありますが、
今回さこつさんが外部化したJavaScriptの中身は
```
/* Check for native pointer event support before PEP adds its polyfill */
if (window.PointerEvent) {
    window.hasNativePointerEvents = true;
}
```
こうなっています。
これは、全く別のコードです。
`fix.js`として外部化されているため、
`fix.js`
の中身を
```
function load() {
document.addEventListener("dblclick", function(e){ e.preventDefault();}, { passive: false });
}
window.onload = load;
```
に修正しても、iPadなどのデバイスでは、キャッシュを読み込んでしまうため、誤動作の原因になります。
外部化をやめてPaintのHTMLの内部に記述する形に戻し、そして、正しいJavaScriptに置き換えるべきでしょう。

>正解を知っているのか知らないのか」がわからないのでそれをお教え願います。

たとえばプルリクすれば、該当箇所はたしかにわかりやすいです。
しかし、今回のような内容の場合は、さこつさんが自分で考える必要があると思いました。

**Comment by sakots** [comment]
書き直させた後結局プルリクが来るのは一体どういう意図ですか

**Comment by satopian** [comment]
結局プルリクしないと何をどうしたらいいのかわからなそうだったからです。
プルリクはクローズします。

**Comment by sakots** [comment]
忙しいだけです

**Comment by satopian** [comment]
意図があるとしたら、別のスクリプトでいろいろな問題があっても私の守備範囲外ですが、POTIはこちらでサポートをやっていますから、それで動作不良の原因を作らないで欲しいという事です。
現状では、さこつさんのテーマが原因で動作しなかったというケースはこちらではサポートしきれません。

**Comment by sakots** [comment]
まずデフォルトのテーマでも起きる問題なのか確認してもらって、それで解決するなら
「テーマが原因なのでテーマの作者までお願いします」で済む問題ではないですか？
それともその手間も惜しいですか？

**Comment by satopian** [comment]
POTIの対応にはとても多くの時間を費やしています。お願いですから、手間を増やさないでください。

**Comment by sakots** [comment]
わざわざ自分で全部背負い込んだのにそういうんですか。

**Comment by satopian** [comment]
一緒に続けていたら楽…では決してなかったのでこちらでやってます。
今回の件のように意思の疎通がうまくいかないからです。
私にも原因はあると思いますが、こうして話している時間を休息にあてる事もできるはずですがそうなりません。

**Comment by sakots** [comment]
- 結局さとぴあさんが全部自分の意見を曲げなかったので、POTIは全部やってもらうことにした
- 好き勝手やるために別れたのに、それにすら注文が入ってくるようになった

もはや意味がわかりません。

**Comment by satopian** [comment]
好き勝手やるにしても、見た目の問題ではなく、動作に関わらる内容ですから。
変更点についてドキュメントを出すなり、リポジトリがあるところには、プルリクを出すなりする事になる。
それがユーザーの利益につながると考えての事です。
POTI-boardでは無い別のお絵かき掲示板であれば、私のところに問い合わせが来る事もないし、私が責任を感じる事もないので、さこつさんがこうしたいと思うようにすればいいのです。
>好き勝手やるために別れたのに、それにすら注文が入ってくるようになった

>chickenpaintの問題に対処するcss/jsは外部化すべき · Issue 5 
https://github.com/satopian/poti-kaini/issues/5

矛盾していると思います。
さこつさんもこうするべきだと意見を述べているので、私がテーマに関して意見を述べたから問題だというのはそれは違うと思います。

**Comment by sakots** [comment]
一切矛盾はありません。
「さとぴあさんは好き勝手したかったが私はそうではなかった」ので。

**Comment by satopian** [comment]
さこつさんの考え方はよくわかりました。賛同はできませんが…。

**Comment by satopian** [comment]
一応これだけは伝えて起きたいので、追記します。
とにかく、内容が内容です。
- iPad + Apple Pencil の時のトラブルの解消
- Windows、MAC、Androidでは発生しない問題
そうなると、問題なく設置できたし設置した人には問題があるように見えないけれど、iPadユーザーは困っているかもしれない。
そういう問題のfixだったりすると、問い合わせが来る来ない以前に、このお絵かき掲示板、うまく描けないからダメだねと思う人が出てくるかもしれない。
事前にそれを回避するには、こうして関わるほかない。
その関わり方や言い方に問題があったのかもしれませんが、問題点に気がついたら連絡をするのは必要な事だと思います。

**Comment by sakots** [comment]
問題点に気がついたら連絡をする、これは同意します。

**Comment by sakots** [comment]
なぜ閉じる。

**Comment by satopian** [comment]
ここで閉じたほうが平和的だと思ったからです。
このプログラムの問題をどうするのかに立ち返った時点でクローズできたほうが良いと考えたからです。
私は、これ以上この議論に時間を割きたくありません。
オープンでも構いませんが、それは、さこつさんにとってもあまりよい事ではないのではないでしょうか。
しかしそれを決めるのはさこつさんですので、おまかせします。

**Comment by sakots** [comment]
fix.jsが必要なくなるまで開いておくべきと思いました。

**Comment by satopian** [comment]
`chickenpaint.js`に
ダブルタップズーム対策として
```
    uiElem.addEventListener("dblclick", function (e) {
      e.preventDefault();
      e.stopPropagation();
    });

```
は追加されましたが、ChickenPaintの起動画面の外側、つまりPOTI-boardのバージョン情報のあたりをダブルタップした時に
意図しないダブルタップズームが起きないようにするには、
`fix.js`も必要です。
著作表示近くのダブルタップの問題は、POTI-boardで対応するべき箇所だと思います。
つまり、ダブルタップズーム対策のJavaScriptは、これからも必要だという認識です。
また、ChickenPaint exampleのアプリ起動画面のhtmlのソースに
```
body {
			-webkit-user-select: none; /* For iOS Safari: Prevent long-press from popping up a selection dialog on body text */
		}
が追加されている事を考えると
fix.cssも現状のままが望ましいと思います。
どうしても、このCSSを短くしたいのであれば
```
:not(input), div#chickenpaint-parent :not(input) {
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
を
```
:not(input) {
    -webkit-user-select: none;
    user-select: none;
}
```
とする事もできますが、どちらにしても、`<body>`に指定するのではなく入力処理以外の時は画面を選択しない
`:not(input)`のほうがベターだと考えます。
つまり、
`fix.css`も、`fix.js`も、ChickenPaintが更新されるまでの一時的なものではなくこのまま使い続けます。
ただし、それによって別途問題が発生するようであれば、見直します。
